// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SiloTower.Domain.DB
{
    public partial class IndicatorValues
    {
        public IndicatorValues()
        {
            TowerLevel = new HashSet<Tower>();
            TowerWeight = new HashSet<Tower>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Value { get; set; }
        public decimal MinValue { get; set; }
        public decimal MaxValue { get; set; }
        public short Type { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<Tower> TowerLevel { get; set; }
        public virtual ICollection<Tower> TowerWeight { get; set; }
    }
}