// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SiloTower.Domain.DB
{
    public partial class Tower
    {
        public int Id { get; set; }
        public int TowerId { get; set; }
        public int IndicatorId { get; set; }

        public virtual IndicatorValues Indicator { get; set; }
    }
}