// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SiloTower.Domain.DB;

#nullable disable

namespace SiloTower.Infrastructure.DB
{
    public partial class SilotowerContext : DbContext
    {
        public SilotowerContext()
        {
        }

        public SilotowerContext(DbContextOptions<SilotowerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<IndicatorValues> IndicatorValues { get; set; }
        public virtual DbSet<Tower> Tower { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS");

            modelBuilder.Entity<IndicatorValues>(entity =>
            {
                entity.Property(e => e.Date)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.MaxValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.MinValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.Title).HasMaxLength(50);

                entity.Property(e => e.Value).HasColumnType("numeric(18, 0)");
            });

            modelBuilder.Entity<Tower>(entity =>
            {
                entity.HasOne(d => d.Level)
                    .WithMany(p => p.TowerLevel)
                    .HasForeignKey(d => d.LevelId);

                entity.HasOne(d => d.Weight)
                    .WithMany(p => p.TowerWeight)
                    .HasForeignKey(d => d.WeightId);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}